# Generated by Django 4.0 on 2022-01-01 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_first_name_remove_account_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
